# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Installing Node JS
        uses: actions/setup-node@v1.4.3
        
      - name : Installing Create-React-App
        uses: npm install -g create-react-app
      - name : Installing yarn
        uses: npm install -g yarn 
         
      - name : Install surge
        uses: npm install -g surge
      
      - name : Create build
        uses: yarn build ./
      
      - name : Deploying on surge
        uses: surge ./build assignment2bootcamp2020.surge.sh --token "daeade17b4f7c6cf7c20d860d0a56feb"
        
        
        
        
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
